import MediaScannerKit

typealias ScanStructurePolicy = MediaScannerKit.ScanStructurePolicy
typealias ScanMetadataPolicy = MediaScannerKit.ScanMetadataPolicy
typealias ScanPluginDescriptor = MediaScannerKit.ScannerPluginDescriptor
typealias ScanRoute = MediaScannerKit.ScannerRoute
typealias ScanPluginRegistry = MediaScannerKit.ScannerPluginRegistry
typealias ScanMode = MediaScannerKit.ScanMode
typealias ScanItemState = MediaScannerKit.ScanItemState
typealias ScanItemIdentity = MediaScannerKit.ScanItemIdentity
typealias ScanFingerprint = MediaScannerKit.ScanFingerprint
typealias ScanInventoryItem = MediaScannerKit.ScanInventoryItem
