import Foundation
import MediaScannerKit

typealias ScanCandidate = MediaScannerKit.ScanCandidate
typealias ScanArchiveMember = MediaScannerKit.ScanArchiveMember
typealias ScanArchiveListing = MediaScannerKit.ScanArchiveListing
typealias ScanTrackMetadata = MediaScannerKit.ScanTrackMetadata
typealias ScanInspection = MediaScannerKit.ScanInspection
typealias ScanFailureStage = MediaScannerKit.ScanFailureStage
typealias ScanFailure = MediaScannerKit.ScanFailure
typealias ScanPipelineResult = MediaScannerKit.ScanPipelineResult
typealias ScanArchiveProvider = MediaScannerKit.ScanArchiveProvider
typealias ScanFormatHandler = MediaScannerKit.ScanFormatHandler
typealias ScanPluginHandlerRegistry = MediaScannerKit.ScanPluginHandlerRegistry
typealias ScanResultSink = MediaScannerKit.ScanResultSink
typealias ScanSummary = MediaScannerKit.ScanSummary
typealias ScanPhaseTelemetry = MediaScannerKit.ScanPhaseTelemetry
typealias ScanPhaseTimeline = MediaScannerKit.ScanPhaseTimeline
typealias ScanResultAccumulator = MediaScannerKit.ScanResultAccumulator
