#pragma once

#include <stdint.h>

typedef void *cocoaspice_ffmpeg_audio_handle_t;

cocoaspice_ffmpeg_audio_handle_t cocoaspice_ffmpeg_audio_open(const char *path, int output_sample_rate);
void cocoaspice_ffmpeg_audio_close(cocoaspice_ffmpeg_audio_handle_t handle);
int cocoaspice_ffmpeg_audio_read(cocoaspice_ffmpeg_audio_handle_t handle, int16_t *samples, int frames);
int cocoaspice_ffmpeg_audio_finished(cocoaspice_ffmpeg_audio_handle_t handle);
int cocoaspice_ffmpeg_audio_sample_rate(cocoaspice_ffmpeg_audio_handle_t handle);
int64_t cocoaspice_ffmpeg_audio_played_frames(cocoaspice_ffmpeg_audio_handle_t handle);
int64_t cocoaspice_ffmpeg_audio_length_frames(cocoaspice_ffmpeg_audio_handle_t handle);
void cocoaspice_ffmpeg_audio_seek(cocoaspice_ffmpeg_audio_handle_t handle, int64_t frame);
const char *cocoaspice_ffmpeg_audio_title(cocoaspice_ffmpeg_audio_handle_t handle);
const char *cocoaspice_ffmpeg_audio_format_name(cocoaspice_ffmpeg_audio_handle_t handle);
